const cfg={...(window.COURSE_CONFIG||{})};
const qs=new URLSearchParams(location.search);
document.documentElement.style.setProperty('--yellow',cfg.accent||'#ffd43b');
document.getElementById('brandName').textContent=cfg.brandName||'Talk Academy';
document.getElementById('lessonTitle').textContent=cfg.lessonTitle||'Build Your Own Words';

const vocab=[
 {word:'teacher',verb:'teach',meaning:'a person who teaches',example:'My teacher helps me learn.',image:'assets/teacher.jpg',tag:'TEACH + ER',prompt:'Who teaches you English?'},
 {word:'driver',verb:'drive',meaning:'a person who drives',example:'My father is a taxi driver.',image:'assets/driver.jpg',tag:'DRIVE + R',prompt:'Who drives a bus or a taxi?'},
 {word:'painter',verb:'paint',meaning:'a person who paints',example:'My sister is a painter.',image:'assets/painter.jpg',tag:'PAINT + ER',prompt:'What does a painter create?'},
 {word:'farmer',verb:'farm',meaning:'a person who works on a farm',example:'John is a farmer.',image:'assets/farmer.jpg',tag:'FARM + ER',prompt:'What can a farmer grow?'},
 {word:'builder',verb:'build',meaning:'a person who builds',example:'The builder is working on a house.',image:'assets/builder.jpg',tag:'BUILD + ER',prompt:'What can a builder build?'},
 {word:'speaker',verb:'speak',meaning:'a person who is speaking',example:'The speaker talks very clearly.',image:'assets/speaker.jpg',tag:'SPEAK + ER',prompt:'What makes a good speaker?'},
 {word:'reader',verb:'read',meaning:'a person who reads',example:'She is a reader of famous novels.',image:'assets/reader.jpg',tag:'READ + ER',prompt:'What do you like to read?'}
];

const questions=[
 ['My brother loves to paint landscapes. He is a great ______.','painter'],
 ['The person who drives our school bus is a ______.','driver'],
 ['My uncle grows corn and wheat. He is a ______.','farmer'],
 ['The person who built this house is a skilled ______.','builder'],
 ['The woman teaching the lesson is my ______.','teacher']
];

const hints={
 ar:[
  'رحّب بالطالب، وتأكد من وضوح الصوت والصورة، ثم ابدأ مباشرة.',
  'قدّم وعد الدرس ببساطة: سنحوّل الأفعال إلى كلمات تدل على الأشخاص.',
  'عرّف بنفسك باختصار. لا تقرأ النصوص الإرشادية حرفيًا.',
  'دع الطالب يختار سؤالين أو ثلاثة فقط حتى يبقى الإيقاع سريعًا.',
  'اطلب من الطالب اختيار مهنة مستقبلية وشرح السبب بجملة بسيطة.',
  'اقرأ المثالين، ثم اطلب من الطالب ملاحظة الجزء المشترك في الكلمتين.',
  ...Array(7).fill('انقر على بطاقة الفعل أولًا، ثم اطلب من الطالب قول الكلمة والجملة كاملة.'),
  'اطلب من الطالب اكتشاف النمط قبل إظهار القاعدة.',
  'أظهر القاعدة بعد إجابة الطالب، ثم أعط مثالًا جديدًا.',
  'اشرح أن goalkeeper كلمة مركبة: goal + keeper.' ,
  'اختر سؤالًا ثم اختر الإجابة. اطلب جملة كاملة بعد كل إجابة صحيحة.',
  'استخدم التحدي للتأكد من أن الطالب يستطيع بناء كلمة جديدة بنفسه.',
  'راجع الكلمات بسرعة، ولا تطلب من الطالب حفظ جميع الجمل.',
  'اطلب من الطالب مثالًا واحدًا من حياته.',
  'اكتب ملاحظات قصيرة قابلة للتنفيذ للدرس القادم.',
  'استخدم مستوى CEFR كمرجع داخلي، وليس كاختبار مباشر للطالب.'
 ],
 en:Array(23).fill('Keep the learner speaking. Ask for one complete sentence before moving on.')
};

function art(src,alt){return `<div class="art-frame"><img src="${src}" alt="${alt}"></div>`}
function vocabScene(v,i){return {stage:`Vocabulary ${i+1} of 7`,title:`Teach: ${v.word}`,render:()=>`<section class="scene vocab-scene"><article class="role-card" data-number="${i+1}"><span class="kicker">${v.tag}</span><div class="word">${v.word} <small>noun</small></div><p class="definition">${v.meaning}</p><div class="morph-builder"><button class="morph source" data-reveal>${v.verb}</button><span>+</span><button class="morph ending" data-reveal>${v.word.endsWith('driver')?'r':'er'}</button><span>=</span><strong>${v.word}</strong></div><p class="example-line">“${v.example}”</p><button class="talk-prompt">${v.prompt}</button></article>${art(v.image,v.word)}</section>`}}
function practiceScene(){return {stage:'Practice',title:'Build the correct word',render:()=>`<section class="scene center practice-scene"><div class="wide"><span class="kicker">1. Choose a sentence · 2. Choose a word</span><h2>Who is this person?</h2><div class="fill-grid">${questions.map((q,i)=>`<button class="fill-card" data-answer="${q[1]}"><b>${i+1}.</b> ${q[0]}<span>Tap this sentence first</span></button>`).join('')}</div><div class="word-bank compact-bank">${['teacher','driver','painter','farmer','builder'].map(w=>`<button class="word-chip" data-fill="${w}">${w}</button>`).join('')}</div><div class="feedback" id="fillFeedback">Choose a sentence, then choose the missing word.</div></div></section>`}}

const scenes=[
 {stage:'الاستعداد',title:'مرحبًا بك',render:()=>`<section class="scene welcome-scene"><article class="welcome-card" dir="rtl" lang="ar"><span class="kicker">رحلة تعلم تفاعلية</span><h1>مرحبًا بك في رحلة تعلم اللغة الإنجليزية!</h1><p class="lead">استعد لتجربة تعلم ممتعة وتفاعلية.</p><div class="ready-grid"><span>🎤 تأكد من أن الميكروفون يعمل</span><span>📷 قم بتشغيل الكاميرا</span><span>📶 تحقق من اتصال الإنترنت</span><span>📝 حضّر ورقة وقلمًا</span></div></article>${art('assets/teacher-avatar.png','Friendly teacher')}</section>`},
 {stage:'Lesson promise',title:'Build your own English words',render:()=>`<section class="scene hook-scene"><div class="hook-copy"><span class="kicker">YOUR 25-MINUTE WORD-BUILDING CHALLENGE</span><h1 class="hero-title hook-sentence"><span>In 25 minutes, you’ll turn actions into people—</span><span class="yellow-mark">and build your own English words!</span></h1><p class="lead">One powerful ending makes it possible: <b>-er</b>.</p><div class="fact-grid"><span>teach → teacher</span><span>drive → driver</span><span>read → reader</span></div></div>${art('assets/blocks.png','Colorful alphabet blocks for building English words')}</section>`},
 {stage:'Meet your teacher',title:'Teacher introduction',render:()=>`<section class="scene profile-scene">${art('assets/teacher-avatar.png','Teacher avatar')}<article class="role-card"><span class="kicker">HELLO!</span><h2>Meet Your Teacher</h2><div class="profile-list teacher-prompts"><span><b>Experience</b><small>Add one short sentence</small></span><span><b>Achievement</b><small>Add one relevant example</small></span><span><b>Teaching style</b><small>Friendly · interactive · encouraging</small></span></div></article></section>`},
 {stage:'Meet the learner',title:'Tell me about yourself',render:()=>`<section class="scene center"><div class="wide"><span class="kicker">Choose any question</span><h2>Tell Me About Yourself!</h2><div class="choice-grid intro-grid"><button class="choice"><b>Your name</b><span>What should I call you?</span></button><button class="choice"><b>Your hobbies</b><span>What do you love to do?</span></button><button class="choice"><b>Favorite subject</b><span>Which class do you enjoy most?</span></button><button class="choice"><b>English goal</b><span>What do you want to achieve?</span></button></div></div></section>`},
 {stage:'Think deeper',title:'Your future',render:()=>`<section class="scene"><div><span class="kicker">LOOK AHEAD</span><h1>What do you want to do<br><span class="yellow-mark">in the future?</span></h1><div class="talk-list"><button class="talk-line">I want to be a ______.</button><button class="talk-line">I want to ______ every day.</button><button class="talk-line">I like this job because ______.</button></div></div>${art('assets/careers.png','Different future careers')}</section>`},
 {stage:'Notice the pattern',title:'Action becomes a person',render:()=>`<section class="scene center"><div class="pattern-card"><span class="kicker">LOOK · SAY · NOTICE</span><h2>An action can name a person</h2><div class="pattern-examples"><button><small>A person who</small><b>teaches</b><span>is a</span><strong>teacher</strong></button><button><small>A person who</small><b>drives</b><span>is a</span><strong>driver</strong></button></div><p class="lead">What changed?</p></div></section>`},
 ...vocab.map(vocabScene),
 {stage:'Discover',title:'Find the pattern',render:()=>`<section class="scene center"><div class="wide"><span class="kicker">FIND SOMETHING</span><h2>What do these words have in common?</h2><div class="word-ladder">${vocab.slice(0,6).map(v=>`<button data-pair><span>${v.verb}</span><b>→</b><strong>${v.word}</strong></button>`).join('')}</div><div class="feedback">Tap each pair. Say the change out loud.</div></div></section>`},
 {stage:'Unlock the rule',title:'What does -er do?',render:()=>`<section class="scene rule-scene"><article class="rule-hero"><span class="kicker">THE MAGIC OF -ER</span><h1><span class="yellow-mark">verb + er</span><br>= person</h1><p class="lead">The suffix <b>-er</b> often turns an action into the person who performs it.</p><div class="formula-strip"><span>teach</span><b>+</b><span>-er</span><b>=</b><strong>teacher</strong></div></article>${art('assets/painter.jpg','A painter performing an action')}</section>`},
 {stage:'Word building',title:'Goalkeeper',render:()=>`<section class="scene vocab-scene"><article class="role-card"><span class="kicker">A COMPOUND WORD</span><div class="word">goalkeeper</div><p class="definition">the player who protects the goal</p><div class="compound"><button data-reveal>goal</button><span>+</span><button data-reveal>keeper</button><span>=</span><strong>goalkeeper</strong></div><div class="steps-list"><p><b>keep</b> → guard or protect</p><p><b>keeper</b> → a person who keeps</p><p><b>goalkeeper</b> → the person who protects the goal</p></div></article>${art('assets/goalkeeper.png','Goalkeeper protecting the goal')}</section>`},
 practiceScene(),
 {stage:'Mini challenge',title:'Create a new -er word',render:()=>`<section class="scene mini-word"><article class="challenge-panel"><span class="kicker">YOU CAN BUILD IT</span><h2>Who does the action?</h2><p class="lead">Choose an action, add <b>-er</b>, then say the new word.</p><div class="challenge-options"><button data-build="teach">teach</button><button data-build="paint">paint</button><button data-build="farm">farm</button><button data-build="read">read</button></div><div class="challenge-sentence" id="buildResult">verb + er = person</div><p id="buildFeedback" class="challenge-feedback">Choose one action.</p></article>${art('assets/blocks.png','Alphabet blocks')}</section>`},
 {stage:'Review',title:'Your -er word collection',render:()=>`<section class="scene center"><div class="wide"><span class="kicker">YOUR COLLECTION</span><h2>Seven words unlocked!</h2><div class="collection">${vocab.map(v=>`<button data-review><small>${v.verb}</small><strong>${v.word}</strong></button>`).join('')}</div><div class="recap-grid"><div class="recap"><strong>7</strong>new words</div><div class="recap"><strong>1</strong>word-building rule</div><div class="recap"><strong>100%</strong>your effort</div></div></div></section>`},
 {stage:'Speak',title:'Use one word',render:()=>`<section class="scene center"><div class="transfer-card"><span class="kicker">MAKE IT YOURS</span><h1>Choose one word.<br><span class="yellow-mark">Make one sentence.</span></h1><div class="sentence-frame">A ______ is a person who ______.</div><div class="word-bank">${vocab.map(v=>`<button class="word-chip" data-transfer="${v.word}">${v.word}</button>`).join('')}</div><p id="transferPrompt" class="feedback">Example: A teacher is a person who teaches.</p></div></section>`},
 {stage:'ملاحظات المعلم',title:'Teacher reflection',render:()=>`<section class="scene center"><div class="wide"><span class="kicker">ملاحظات المعلم</span><h2>Teacher Notes</h2><div class="note-grid" dir="rtl" lang="ar"><div>مستوى الطالب<b>Student level</b></div><div>نقاط القوة<b>Strengths</b></div><div>مجالات التحسين<b>Areas to improve</b></div><div>اقتراحات للتعلم<b>Learning suggestions</b></div></div></div></section>`},
 {stage:'CEFR reference',title:'CEFR levels and key abilities',render:()=>`<section class="scene center"><div class="wide"><span class="kicker">TEACHER REFERENCE</span><h2>CEFR Levels & Key Abilities</h2><div class="cefr-grid"><div><strong>C2</strong><span>Understands virtually everything; summarizes and evaluates complex information.</span></div><div><strong>C1</strong><span>Uses language flexibly and effectively in academic, social, and professional contexts.</span></div><div><strong>B2</strong><span>Understands main ideas of complex texts and interacts with fluency.</span></div><div><strong>B1</strong><span>Handles familiar topics and most travel situations; gives simple explanations.</span></div><div><strong>A2</strong><span>Uses common expressions and communicates in routine tasks.</span></div><div><strong>A1</strong><span>Uses basic phrases, introduces oneself, and asks simple questions.</span></div></div></div></section>`}
];

let index=Math.max(0,Math.min(scenes.length-1,(Number(qs.get('scene'))||1)-1)),selectedQuestion=null;
const lesson=document.getElementById('lesson'),progressBar=document.getElementById('progressBar'),progressText=document.getElementById('progressText');
function render(){const s=scenes[index];lesson.innerHTML=s.render();document.getElementById('stageLabel').textContent=s.stage;document.getElementById('teacherTitle').textContent=s.title;document.getElementById('teacherCopy').textContent=(hints[cfg.teacherHintLanguage]||hints.en)[index]||hints.en[0];progressBar.style.width=`${(index+1)/scenes.length*100}%`;progressText.textContent=`${index+1} / ${scenes.length}`;document.getElementById('prevBtn').disabled=index===0;document.getElementById('nextBtn').innerHTML=index===scenes.length-1?'Restart ↻':'Next <span>→</span>';bindScene()}
function bindScene(){selectedQuestion=null;document.querySelectorAll('.choice,.talk-line,.talk-prompt,[data-pair],[data-review],[data-reveal]').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));document.querySelectorAll('.fill-card').forEach(b=>b.onclick=()=>{selectedQuestion=b;document.querySelectorAll('.fill-card').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('fillFeedback').textContent='Now choose the missing word.'});document.querySelectorAll('[data-fill]').forEach(b=>b.onclick=()=>{const f=document.getElementById('fillFeedback');if(!selectedQuestion){f.textContent='Choose a sentence first.';return}const ok=b.dataset.fill===selectedQuestion.dataset.answer;selectedQuestion.classList.toggle('correct',ok);selectedQuestion.classList.toggle('wrong',!ok);selectedQuestion.querySelector('span').textContent=ok?`Correct — ${b.dataset.fill}`:`Try again — ${b.dataset.fill} does not fit.`;f.textContent=ok?'Great! Say the full sentence.':'Try another word.';if(ok)selectedQuestion=null});document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-build]').forEach(x=>x.classList.toggle('selected',x===b));const w=b.dataset.build+(b.dataset.build==='drive'?'r':'er');document.getElementById('buildResult').textContent=`${b.dataset.build} + er = ${w}`;document.getElementById('buildFeedback').textContent=`Great! Now say: “A ${w} is a person who ${b.dataset.build}s.”`});document.querySelectorAll('[data-transfer]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-transfer]').forEach(x=>x.classList.toggle('selected',x===b));const v=vocab.find(x=>x.word===b.dataset.transfer);document.getElementById('transferPrompt').textContent=`A ${v.word} is ${v.meaning}.`})}
function go(n){index=(n+scenes.length)%scenes.length;render()}
document.getElementById('prevBtn').onclick=()=>go(index-1);document.getElementById('nextBtn').onclick=()=>go(index===scenes.length-1?0:index+1);document.getElementById('homeBtn').onclick=()=>go(0);document.getElementById('teacherBtn').onclick=()=>document.getElementById('teacherPanel').showModal();document.getElementById('restartBtn').onclick=()=>{document.getElementById('teacherPanel').close();go(0)};document.getElementById('revealBtn').onclick=()=>{document.querySelectorAll('.fill-card').forEach(b=>{b.classList.add('correct');b.querySelector('span').textContent=b.dataset.answer});document.querySelectorAll('[data-reveal],[data-pair]').forEach(b=>b.classList.add('selected'))};document.getElementById('soundBtn').style.display='none';document.getElementById('fullBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();document.addEventListener('keydown',e=>{if(e.key==='ArrowRight')go(index+1);if(e.key==='ArrowLeft')go(index-1);if(e.key.toLowerCase()==='t')document.getElementById('teacherPanel').showModal()});render();
